// USER
export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_REGISTER = 'USER_REGISTER'
export const AUTHORIZE_USER = 'AUTHORIZE_USER'

// USER PROFILE
export const USER_BIRTHDAY = 'USER_BIRTHDAY'
export const USER_NAME_AND_LASTNAME = 'USER_NAME_AND_LASTNAME'
export const USER_OCCUPATION = 'USER_OCCUPATION'
export const USER_NATIONALITY = 'USER_NATIONALITY'
export const USER_IS_USER_SMOKER = 'USER_IS_USER_SMOKER'
